name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'fio_stac/**.py'
      - .github/workflows/deploy_mkdocs.yml

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .["doc"]

      - name: update API docs
        run: |
          pdocs as_markdown --output_dir docs/docs/api/ --exclude_source --overwrite fio_stac.stac

      - name: Deploy docs
        run: mkdocs gh-deploy -f docs/mkdocs.yml --force
